### ISSUE TITLE
setup-qemu-action fails to pull docker image

### ISSUE THREAD

**Issue by benfred** [docker/setup-qemu-action#107]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-qemu-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Using this action fails on pulling the docker image

```
Error response from daemon: Get "https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/sha256:66e11bea77a5ea9d6f0fe79b57cd2b189b5d15b93a2bdb925be22949232e4e55": EOF
```
Trying to pull the same docker image on my own workstation also fails with the same error

### Expected behaviour

Action should pull docker image

### Actual behaviour

Fails with 
```
Error response from daemon: Get "https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/sha256:66e11bea77a5ea9d6f0fe79b57cd2b189b5d15b93a2bdb925be22949232e4e55": EOF
```

### Repository URL

https://github.com/benfred/implicit

### Workflow run URL

https://github.com/benfred/implicit/actions/runs/6344238321/job/17233934671#step:3:101

### YAML workflow

```yaml
# modified from https://github.com/benfred/implicit/blob/main/.github/workflows/build.yml
name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

  build-wheels:
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [36, 37, 38, 39, 310, 311]
        cibw-arch: [auto, aarch64]
        exclude:
          - os: macos-latest
            cibw-arch: aarch64
          - os: windows-latest
            cibw-arch: aarch64

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
```

### Workflow logs

```
Run docker/setup-qemu-action@v3
Docker info
Pulling binfmt Docker image
  /usr/bin/docker pull tonistiigi/binfmt:latest
  Error response from daemon: Head "https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/latest": EOF
Error: The process '/usr/bin/docker' failed with exit code 1
```
