### ISSUE TITLE
Error while pulling tonistiigi/binfmt:latest image

### ISSUE THREAD

**Issue by lunacrafts** [docker/setup-qemu-action#110]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-qemu-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

Run docker/setup-qemu-action@v3

Pulling binfmt Docker image
  /usr/bin/docker pull tonistiigi/binfmt:latest
  Error response from daemon: Head "https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/latest": EOF
Error: The process '/usr/bin/docker' failed with exit code 1

### Expected behaviour

-----

### Actual behaviour

-----

### YAML workflow

```yaml
name: build_and_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - pnpm-lock.yaml
      - .github/**
      - mirrorboards/**
      - mirrorboards-server/**
      - Dockerfile.mirrorboards
      - envs/**

env:
  REGISTRY: 'docker.io/lunacrafts'
  KUBECONFIG: ./kubeconfig.yaml
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: npx turbo run build '--filter=./mirrorboards/**' '--filter=./mirrorboards-server/*'

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.mirrorboards
          push: true
          tags: lunacrafts/mirrorboards:${{ github.sha }}

  deploy:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: 'boards'
            path: 'mirrorboards/boards/boards-box'

          - service: 'hypeboards-telegram-bot'
            path: 'mirrorboards/hypeboards/hypeboards-telegram-bot'

          - service: 'hypeboards-box'
            path: 'mirrorboards/hypeboards/hypeboards-box'

          - service: 'mirrorboards-server'
            path: 'mirrorboards-server/mirrorboards-server'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure k8s context
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig.yaml
      - name: deploy helm
        run: |
          helm upgrade --install --namespace "mirror" ${{matrix.service}} ./${{matrix.path}}/helm --set image_tag="${{ github.sha }}"
```

### BuildKit logs

```text
Run docker/setup-qemu-action@v3
  with:
    image: tonistiigi/binfmt:latest
    platforms: all
  env:
    REGISTRY: docker.io/***
    KUBECONFIG: ./kubeconfig.yaml
    TURBO_TEAM: team_EErnrsQkD8EbJ5K61AYeUW9N
    TURBO_TOKEN: ***
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
Docker info
  /usr/bin/docker version
  Client: Docker Engine - Community
   Version:           24.0.7
   API version:       1.43
   Go version:        go1.20.10
   Git commit:        afdd53b
   Built:             Thu Oct 26 09:07:41 2023
   OS/Arch:           linux/amd64
   Context:           default
  
  Server: Docker Engine - Community
   Engine:
    Version:          24.0.7
    API version:      1.43 (minimum version 1.12)
    Go version:       go1.20.10
    Git commit:       311b9ff
    Built:            Thu Oct 26 09:07:41 2023
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.6.24
    GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
   runc:
    Version:          1.1.9
    GitCommit:        v1.1.9-0-gccaecfc
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  /usr/bin/docker info
  Client: Docker Engine - Community
   Version:    24.0.7
   Context:    default
   Debug Mode: false
   Plugins:
    buildx: Docker Buildx (Docker Inc.)
      Version:  v0.11.2
      Path:     /usr/libexec/docker/cli-plugins/docker-buildx
    compose: Docker Compose (Docker Inc.)
      Version:  v2.23.0
      Path:     /usr/libexec/docker/cli-plugins/docker-compose
  
  Server:
   Containers: 0
    Running: 0
    Paused: 0
    Stopped: 0
   Images: 19
   Server Version: 24.0.7
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Using metacopy: false
    Native Overlay Diff: false
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: cgroupfs
   Cgroup Version: 2
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
   runc version: v1.1.9-0-gccaecfc
   init version: de40ad0
   Security Options:
    apparmor
    seccomp
     Profile: builtin
    cgroupns
   Kernel Version: 6.2.0-1015-azure
   Operating System: Ubuntu 22.04.3 LTS
   OSType: linux
   Architecture: x86_64
   CPUs: 2
   Total Memory: 6.76GiB
   Name: fv-az301-86
   ID: 5ee0a90d-9ba7-4120-a52c-7d8898402fd7
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Username: githubactions
   Experimental: false
   Insecure Registries:
    127.0.0.0/8
   Live Restore Enabled: false
  
Pulling binfmt Docker image
  /usr/bin/docker pull tonistiigi/binfmt:latest
  Error response from daemon: Head "https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/latest": EOF
Error: The process '/usr/bin/docker' failed with exit code 1
```
