### ISSUE TITLE
Purpose of this action?

### ISSUE THREAD

**Issue by kroese** [docker/setup-qemu-action#112]
### Description

In all examples I always see this action used like this:

```yaml
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

But if I omit this action, and just use:

```yaml
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

I can still build ARM64 images using QEMU via Buildx.

So what is the exact purpose of this action? Was it something that was needed in the past and now has become obsolete?
