### ISSUE TITLE
setup-qemu-action not working with recursive option

### ISSUE THREAD

**Issue by ArtemIsmagilov** [docker/setup-qemu-action#150]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-qemu-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

this job not working then i try set `submodules: 'recursive'`

### Expected behaviour

correct working in aarch systems

### Actual behaviour

Error: The process '/usr/bin/docker' failed with exit code 1

### Repository URL

https://github.com/ArtemIsmagilov/emcache

### Workflow run URL

https://github.com/ArtemIsmagilov/emcache/actions/runs/9774907951/job/26984204133

### YAML workflow

```yaml
name: PyPi release
on:
  push
#    tags:
#      - v*

jobs:
  # Use Any Python version, cibuildwheel downloads multiple python version to create each build environment.
  # We can only use x86-64 macOS, so we can test on x86-64. But murmur3 is now universal2 binary. So It'll be works for arm64 too.
  build_linux_aarch64:
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        platforms:
          - linux/arm64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Generate manylinux2014_aarch64-wheel
      run: |
        mkdir /tmp/emcache
        cp -r . /tmp/emcache
        docker run --platform linux/arm64 -v /tmp/emcache:/io -e "PYTHON_VERSION=${{matrix.python-version}}" quay.io/pypa/manylinux_2_28_aarch64 /io/bin/build_manylinux_2_28_wheel.sh
        mkdir test_wheel/
        cp /tmp/emcache/dist/emcache-*.whl test_wheel/
    - name: Run unit tests using the wheel
      run: |
        docker run --platform linux/arm64 --entrypoint bash -v `pwd`:/io python:${{matrix.python-version}}-bookworm /io/bin/test_aarch_wheel.sh
    - name: Get the version
      id: get_version
      run: echo "VERSION=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v3
      with:
        name: aarch64-${{ steps.get_version.outputs.VERSION }}
        path: test_wheel/emcache-*.whl
```
