### ISSUE TITLE
Fail action on unsupported architecture

### ISSUE THREAD

**Issue by jacob-carlborg** [docker/setup-qemu-action#158]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-qemu-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

The action continues to run when an unsupported architecture is specified. The problem is that I specified `mips64el` as the architecture instead of `mips64le`.

### Expected behaviour

I expected the action to fail.

### Actual behaviour

The action continues to run an completes successfully.

### Repository URL

https://github.com/jacob-carlborg/lime

### Workflow run URL

https://github.com/jacob-carlborg/lime/actions/runs/10162079184/job/28101982775

### YAML workflow

```yaml
- name: Set up QEMU
        if: ${{ matrix.data.docker }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: mips64el
```
