### ISSUE TITLE
Incorrect username and password

### ISSUE THREAD

**Issue by D3vil0p3r** [docker/setup-qemu-action#168]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-qemu-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

When I run this GitHub Actions job, I get:
```
Error response from daemon: Head "https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/latest": unauthorized: incorrect username or password
```
There is a closed issue https://github.com/docker/setup-qemu-action/issues/167 with comments mentioning my error but I'm still getting this weird behavior.

### Expected behaviour

Running with no issue.

### Actual behaviour

```
Error response from daemon: Head "https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/latest": unauthorized: incorrect username or password
```

### YAML workflow

```yaml
name: Scheduled Container Publish

on:
  schedule:
    - cron: '22 4 * * 0'
  workflow_dispatch:

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: athenaos/hephaestus:latest
```
