### ISSUE TITLE
Authenticate with DockerHub?

### ISSUE THREAD

**Issue by lukehsiao** [docker/setup-qemu-action#178]
### Description

We are seeing rate limit issues:

![Image](https://github.com/user-attachments/assets/48b93767-6de0-47a2-968e-6883414f5901)

Is there a way to authenticate with DockerHub (so we can get higher rate limits)?

**Comment by crazy-max** [comment]
GitHub public runners don't have rate limits against Docker Hub. I that's the case let us know.

If you're on a self-hosted runner it might happen but you can use https://github.com/docker/login-action:

```yaml
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
```
