### ISSUE TITLE
Support http_proxy when pull tonistiigi/binfmt image

### ISSUE THREAD

**Issue by seepine** [docker/setup-qemu-action#194]
### Description

I'm not sure if it is currently supported. I hope that, similar to the build process, proxy configuration can be supported.

### eg docker/setup-buildx-action
```yml
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          env.http_proxy=${{ env.http_proxy }}
          env.https_proxy=${{ env.https_proxy }}
          "env.no_proxy='${{ env.no_proxy }}'"
```

### eg docker/build-push-action
```yml
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        tags: demo/app:latest
        build-args: |
            "http_proxy='${{ env.http_proxy }}'"
            "https_proxy='${{ env.https_proxy }}'"
```
