### ISSUE TITLE
Docker build fails when apt is installing libc-bin

### ISSUE THREAD

**Issue by bluecamel** [docker/setup-qemu-action#199]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/setup-qemu-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Our CI recently starting failing with a core dump when apt is instalilng libc-bin.  Specifying an older version of the binfmt image works around the issue.

### Expected behaviour

No errors and build completes properly.

### Actual behaviour

I see the following error:
```
#34 228.9 Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
#34 229.1 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#34 229.6 Segmentation fault (core dumped)
#34 229.7 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#34 230.1 Segmentation fault (core dumped)
#34 230.1 dpkg: error processing package libc-bin (--configure):
#34 230.1  installed libc-bin package post-installation script subprocess returned error exit status 139
```

I saw that a new image was recently pushed, so went back to the previous version, which doesn't have this issue:
```
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0-28
```

I'm not sure if it matters for this, but we have been on v2 of this action.  I did try the latest and it didn't make a difference.

### YAML workflow

```yaml
The issue is without any customization of the action:

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2


I also tried the latest version with the same results.
```

### BuildKit logs

```text

```
