### ISSUE TITLE
The build works well in a physical raspberry pi but not works in github action arm/v7 qemu pipeline

### ISSUE THREAD

**Issue by juampe** [docker/setup-qemu-action#25]
### Behaviour
The pipeline works well in a physical raspberry pi but not works in github action qemu pipeline

#### Steps to reproduce this issue

1. Create a standard multiarch action 
2. Create a docker file with debian:bullseye and ghc in experimental branch
```
FROM debian:bullseye as builder
ARG TARGETARCH
ARG DEBIAN_FRONTEND="noninteractive"

#Access to ghc 8.10.4 in experimental branch
RUN /bin/echo -ne "deb http://deb.debian.org/debian/ experimental main\ndeb-src http://deb.debian.org/debian/ experimental main" > /etc/apt/sources.list.d/experimental.list && /bin/echo -ne "Package: *\nPin: release a=experimental\nPin-Priority: 1" > /etc/apt/preferences.d/experimental.pref && apt-get -y update

RUN apt-get -y upgrade && apt-get -y install --no-install-recommends apt-utils bash curl wget ca-certificates automake build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev make g++ tmux git jq wget libncursesw5 libtool autoconf iproute2 miniupnpc cabal-install cabal-debian ghc/experimental
```

3. Run the action making a push

#### Expected behaviour

> It may install ghc correctly as it does in a physical raspberry pi
`Docker version 20.10.5, build 55c4c88`
in a raspberry pi
`Linux controller 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux`

#### Actual behaviour

> It generate problems to install ghc. It seems related to virtualization problems [ghc and WSL](https://stackoverflow.com/questions/65197507/ghc-pkg-couldnt-open-database-for-modification-hlock-invalid-argument)
```
#7 82.92 Setting up ghc (8.10.4-1~exp1) ...
#7 83.39 update-alternatives: using /usr/bin/runghc to provide /usr/bin/runhaskell (runhaskell) in auto mode
#7 83.44 update-alternatives: using /usr/bin/ghc to provide /usr/bin/haskell-compiler (haskell-compiler) in auto mode
#7 83.61 ghc-pkg: Couldn't open database /usr/lib/ghc/package.conf.d for modification: {handle: /usr/lib/ghc/package.conf.d/package.cache.lock}: hLock: invalid argument (Invalid argument)
#7 83.63 dpkg: error processing package ghc (--configure):
#7 83.63  installed ghc package post-installation script subprocess returned error exit status 1
#7 83.63 Processing triggers for libc-bin (2.31-9) ...
#7 83.73 Errors were encountered while processing:
#7 83.73  ghc
#7 83.84 E: Sub-process /usr/bin/dpkg returned an error code (1)
#7 ERROR: executor failed running [/bin/sh -c mkdir -p /usr/lib/ghc/package.conf.d/ && touch /usr/lib/ghc/package.conf.d/package.cache.lock && chmod +w /usr/lib/ghc/package.conf.d/package.cache.lock && apt-get -y install --no-install-recommends ghc/experimental]: exit code: 100
------
 > [3/5] RUN mkdir -p /usr/lib/ghc/package.conf.d/ && touch /usr/lib/ghc/package.conf.d/package.cache.lock && chmod +w /usr/lib/ghc/package.conf.d/package.cache.lock && apt-get -y install --no-install-recommends ghc/experimental:
------
Dockerfile:8
--------------------
   6 |     RUN /bin/echo -ne "deb http://deb.debian.org/debian/ experimental main\ndeb-src http://deb.debian.org/debian/ experimental main" > /etc/apt/sources.list.d/experimental.list && /bin/echo -ne "Package: *\nPin: release a=experimental\nPin-Priority: 1" > /etc/apt/preferences.d/experimental.pref && apt-get -y update
   7 |     
   8 | >>> RUN mkdir -p /usr/lib/ghc/package.conf.d/ && touch /usr/lib/ghc/package.conf.d/package.cache.lock && chmod +w /usr/lib/ghc/package.conf.d/package.cache.lock && apt-get -y install --no-install-recommends ghc/experimental 
   9 |     RUN apt-get -y upgrade && apt-get -y install --no-install-recommends apt-utils bash curl wget ca-certificates automake build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev make g++ tmux git jq wget libncursesw5 libtool autoconf iproute2 miniupnpc cabal-install cabal-debian
  10 |     #RUN apt-get clean && apt-get -y install --no-install-recommends ghc/experimental 
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c mkdir -p /usr/lib/ghc/package.conf.d/ && touch /usr/lib/ghc/package.conf.d/package.cache.lock && chmod +w /usr/lib/ghc/package.conf.d/package.cache.lock && apt-get -y install --no-install-recommends ghc/experimental]: exit code: 100
Error: Process completed with exit code 1.
```

### Configuration

* Repository URL (if public): 
https://github.com/juampe/cardano-docker
* Build URL (if public): 
*https://github.com/juampe/cardano-docker/runs/2156625609?check_suite_focus=true

```yml
name: build our image and push to docker.io
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm/v7
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - 
        name: Build the image
        run: |
            docker buildx build --push --tag blah/blahblah:latest --platform linux/arm/v7 .
```

### Logs

> Pipeline logs
[logs_15.zip](https://github.com/docker/setup-qemu-action/files/6177137/logs_15.zip)
