### ISSUE TITLE
Issue with running hangover in ARM container which does work with QUS but not with setup-qemu-action

### ISSUE THREAD

**Issue by devedse** [docker/setup-qemu-action#28]
### Behaviour

I was working on building an ARM image in a docker build pipeline. The image consists of my own image optimization application which is build for windows and contains some external tools that are compiled for x86. Using a tool/program named hangover: https://github.com/AndreRH/hangover.

To build the image I used the task docker/setup-qemu-action@v1. I managed to get everything working including the emulation of x86 windows application on my Raspberry PI 4 (64-bit).

If I however run this exact same image inside my build pipeline it doesn't seem to work. Also running it locally on my own computer with the default docker desktop installation (which I believe also has Qemu support enabled) also fails with a segmentation fault.

![image](https://user-images.githubusercontent.com/2350015/114630593-3eb81180-9cbb-11eb-965d-d59f28b5138f.png)

Here's the actual build pipeline that fails (the `test_docker_linux` job):
https://github.com/devedse/DeveImageOptimizer/actions/runs/746107178

The strange thing is though that if I use qus (https://github.com/dbhi/qus) rather then `setup-qemu-action` the image does seem to run correctly. I'm not really sure why or what the difference is but for some reason there's a difference between the 2.

#### Steps to reproduce this issue

1. Download my container for arm `docker pull --platform linux/arm64 devedse/deveimageoptimizerconsoleapp`
2. Execute setup-qemu-action
3. Run my container `docker run --rm --entrypoint /root/hangover/build/wine-host/loader/wine devedse/deveimageoptimizerconsoleapp:latest /root/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so "/root/.wine/drive_c/Program Files/FileOptimizer/Plugins64/jpegoptim.exe" -o --all-progressive "/app/TestImage.jpg"`

#### Expected behaviour

The container should run and optimize my image

#### Actual behaviour

It doesn't work instead results in a segmentation fault error (exit code 139). (https://www.geeksforgeeks.org/exit-codes-in-c-c-with-examples/#:~:text=exit(139)%3A%20It%20indicates,%2Dof%2Dbounds%20array%20index.)

### Configuration

* Repository URL (if public): https://github.com/devedse/DeveImageOptimizer
* Build URL (if public): https://github.com/devedse/DeveImageOptimizer/actions/runs/746107178

```yml
  test_docker_linux:
    needs: [generate_version_number, build_docker_linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Test docker run
      run: |
        docker pull --platform linux/arm64 devedse/deveimageoptimizerconsoleapp
        #docker run --rm devedse/deveimageoptimizerconsoleapp
        docker run --rm --entrypoint /root/hangover/build/wine-host/loader/wine devedse/deveimageoptimizerconsoleapp:latest /root/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so "/root/.wine/drive_c/Program Files/FileOptimizer/Plugins64/jpegoptim.exe" -o --all-progressive "/app/TestImage.jpg"

  test_docker_linuxqus:
    needs: [generate_version_number, build_docker_linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup qus
      run: |
        docker run --rm --privileged aptman/qus -s -- -p
    - name: Test docker run
      run: |
        docker pull --platform linux/arm64 devedse/deveimageoptimizerconsoleapp
        #docker run --rm devedse/deveimageoptimizerconsoleapp
        docker run --rm --entrypoint /root/hangover/build/wine-host/loader/wine devedse/deveimageoptimizerconsoleapp:latest /root/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so "/root/.wine/drive_c/Program Files/FileOptimizer/Plugins64/jpegoptim.exe" -o --all-progressive "/app/TestImage.jpg"
```

#### test_docker_linux

```
Digest: sha256:38a147ea204c04501f32801a6f1360f677ea18a4c7968eced68febf4f4533af3
Status: Downloaded newer image for devedse/deveimageoptimizerconsoleapp:latest
docker.io/devedse/deveimageoptimizerconsoleapp:latest
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
Error: Process completed with exit code 139.
```

Exit code 139 means Segmentation fault.

#### test_docker_linuxqus

```
Digest: sha256:38a147ea204c04501f32801a6f1360f677ea18a4c7968eced68febf4f4533af3
Status: Downloaded newer image for devedse/deveimageoptimizerconsoleapp:latest
docker.io/devedse/deveimageoptimizerconsoleapp:latest
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
0048:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0050:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x800736b7
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x800736b7
0050:err:ole:apartment_get_local_server_stream Failed: 0x800736b7
0050:err:virtual:virtual_setup_exception stack overflow 1648 bytes in thread 0050 addr 0x7fcfe68da96c stack 0x130990 (0x130000-0x131000-0x230000)
0040:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0040:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0040:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
002c:err:process:NtCreateUserProcess L"\\??\\C:\\windows\\syswow64\\rundll32.exe" not supported on this installation (x86 binary)
0098:err:virtual:virtual_setup_exception stack overflow 2368 bytes in thread 0098 addr 0x7fa7ac54596c stack 0x5606c0 (0x560000-0x561000-0x660000)
0078:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
002c:err:setupapi:SetupDiInstallDevice Failed to start service L"winebus" for device L"ROOT\\WINE\\WINEBUS", error 1053.
wine: configuration in L"/root/.wine" has been updated.
0048:err:virtual:virtual_setup_exception stack overflow 1648 bytes in thread 0048 addr 0x7f4a40a5b96c stack 0x130990 (0x130000-0x131000-0x230000)
00a8:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
00a8:err:virtual:virtual_setup_exception stack overflow 2080 bytes in thread 00a8 addr 0x7f80a607f96c stack 0x1307e0 (0x130000-0x131000-0x230000)
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0024:err:qemu_riched20:qemu_dll_register Failed to instantiate a RICHEDIT_CLASS20A window.
0024:err:qemu_riched20:qemu_dll_register Failed to set WNDPROC of RICHEDIT_CLASS20A.
0024:err:qemu_riched20:qemu_dll_register Failed to instantiate a RichEdit50A window.
0024:err:qemu_riched20:qemu_dll_register Failed to instantiate a RICHEDIT_CLASS20W window.
0024:err:qemu_riched20:qemu_dll_register Failed to set WNDPROC of RICHEDIT_CLASS20W.
0024:err:qemu_riched20:qemu_dll_register Failed to instantiate a MSFTEDIT_CLASS window.
0024:err:secur32:SECUR32_initSchannelSP TLS library not found, SSL connections will fail
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0024:fixme:qemu_ntdll:qemu_RtlAddVectoredExceptionHandler Unverified!
0024:fixme:qemu_ntdll:qemu_RtlFlsAlloc FLS Release callback not implemented
0024:fixme:qemu_ntdll:qemu_RtlFlsAlloc FLS Release callback not implemented
0024:fixme:qemu_kernel32:qemu_SetConsoleCtrlHandler Only partial support.
0024:fixme:qemu_kernel32:qemu_MoveFileExW Unverified!
/app/TestImage.jpg 3000x2000 24bit N Exif XMP ICC JFIF  [OK] 858214 --> 828293 bytes (3.49%), optimized.
```

**Comment by tonistiigi** [comment]
The difference is that default `tonistiigi/binfmt` image is based on qemu 5.0.1 while your case requires qemu-5.2 for some reason.

We can't update to 5.2 atm because regressions https://github.com/docker/buildx/issues/542#issuecomment-778941913 that have not been fixed.

If you want to manually switch to 5.2 use image `tonistiigi/binfmt:qemu-v5.2.0`

**Comment by devedse** [comment]
Thanks for the information. I've done a new build:
https://github.com/devedse/DeveImageOptimizer/actions/runs/751745373

I'll update this issue after the build completes.

**Comment by devedse** [comment]
It seems for now the build gets stuck on something else, so I don't have an update yet:
https://github.com/devedse/DeveImageOptimizer/runs/2356947209?check_suite_focus=true

**Comment by crazy-max** [comment]
@devedse Can you try with `crazymax/binfmt:v6.0.0-rc4`?

**Comment by devedse** [comment]
The build itself does seem to work now either with QEMU 5.2.0 and QUS. So that's good.

What I'm trying to do though is also run the container as a test, it should optimize some images and then display the result.
It seems though that something is going wrong there with https://github.com/AndreRH/hangover in combination with not having the -it parameter for docker. So that's probably not related to this github action anymore but more of a bug in hangover: https://github.com/AndreRH/hangover/issues/114#issuecomment-816303677 (since it does run if I use setup-qemu-action to emulate the whole container with normal x86 wine).

I'm a bit stuck though on how to solve that issue, and without solving that I'm not able to fully verify if running the container is now actually working with either version of Qemu.

So if any of you happen to have some tips on that one, let me know as well :).

**Comment by devedse** [comment]
The builds just completed and it seems the crazymax qemu is the only one that executes both the build and the run.

So hopefully the hangover guys can fix that issue with it getting stuck, then I should be good to go :).

**Comment by crazy-max** [comment]
@devedse Ok great, can you make another test with this one please:

```yaml
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:qemu-v6.0.0
```
