### ISSUE TITLE
gradle tasks are stuck forever on ARM64 image builds

### ISSUE THREAD

**Issue by balusarakesh** [docker/setup-qemu-action#42]
### Behaviour
 - `gradle build` is stuck forever while building ARM64 docker image using `image: tonistiigi/binfmt:latest`
 - here is the process that is stuck forever: 
 ```
 /usr/bin/qemu-aarch64 /usr/lib/jvm/java-1.8.0-amazon-corretto/bin/java -Dorg.gradle.daemon=false -Dorg.gradle.appname=gradlew -classpath /usr/app/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain build -x :bootRepackage -x test --continue
 ```

#### Steps to reproduce this issue

1. use the following workflow and try to build a docker image with the following Dockerfile on the runner pod with image `summerwind/actions-runner-dind:v2.283.1-ubuntu-20.04-24602ff`:
```
jobs:
  docker:
    runs-on: [size/lg]
    steps:
      - name: Set up  QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build/Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/arm64
```

Dockerfile:
```
FROM amazoncorretto:8u302
ENV GRADLE_OPTS=-Dorg.gradle.daemon=false
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME
COPY . .
RUN ./gradlew build -x :bootRepackage -x test --continue
RUN echo "hello"
```

2. gradle version:

```
Gradle 3.5
Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6
Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_302 (Amazon.com Inc. 25.302-b08
```

3. Once the `./gradlew build -x :bootRepackage -x test --continue` command finished running, we can see in the github action logs that the build passed but the runner doesn't proceed to the next step `echo "hello"`. We exec into the runner pod and noticed that the `gradlew` command is still running, for some reason the command exit code is not being received by the `qemu` process OR might be some other issue

#### Expected behaviour
- `./gradlew build -x :bootRepackage -x test --continue` command should finish and the build should proceed to the next step `echo "hello"`

#### Actual behaviour
- gradlew process is stuck forever

### Logs
- unfortunately all the logs look just normal and they contain private build info which I cannot share here
- as you can see in the screenshot the build is stuck for hours and gets terminated when the runner pod is killed
<img width="1098" alt="Screen Shot 2021-09-30 at 12 10 52 PM" src="https://user-images.githubusercontent.com/17168699/135516213-a91ffd78-4610-4d8b-a094-043ef8df8b41.png">
issue.

### workaround
- we noticed that switching to image `qemu-v6.0.0-12` fixed the issue:
```
- name: Set up  QEMU
  uses: docker/setup-qemu-action@v1
  with:
    image: tonistiigi/binfmt:qemu-v6.0.0-12
```
