### ISSUE TITLE
Bumping version from 1.2.0 to 2.0.0 causes network errors pushing to ghcr.io

### ISSUE THREAD

**Issue by felddy** [docker/setup-qemu-action#55]
### Behaviour

A recent dependabot PR caused all builds of the repositories Docker containers to fail to push to the Github container registry: ghcr.io

- https://github.com/felddy/foundryvtt-docker/pull/344

I have been investigating this behavior in an issue in the repository: 
- https://github.com/felddy/foundryvtt-docker/issues/358

I am able to run the workflow with docker/setup-qemu-action `v1.2.0` with success in this branch, and build URL. 

- Branch: https://github.com/felddy/foundryvtt-docker/tree/bugfix/issue-358
- Build URL: https://github.com/felddy/foundryvtt-docker/runs/6630691545?check_suite_focus=true

I am able to reproduce the error consistently here using docker/setup-qemu-action `v2.0.0`:

- Branch: https://github.com/felddy/foundryvtt-docker/tree/debug/quemu-2
- Build URL: https://github.com/felddy/foundryvtt-docker/runs/6630906077?check_suite_focus=true (full log zip attached)
- Note: The`QEMU_STRACE` is set to `1` in this branch workflow

With `v2.0.0` of the action the workflow will consistently error out with:

```console
Error: buildx failed with: error: failed to solve: failed commit on ref "layer-sha256:293d0ab3d70be27758e07257b6690628ae5709b82d2e74f511b0bbbf63da495c": cannot reuse body, request must be retried
```

During the attempt to push to `ghrc.io` there will be several errors similar to the following:
```
#101 30.42 error: failed to copy: failed to do request: Put "https://ghcr.io/v2/***/foundryvtt/blobs/upload/19f65c57-d2c4-40fc-81fb-348af320eca6?digest=sha256%3A9c71462295ef41e80450f962c72e0d5e9f9128b5a07080e84595f0f50fa9d3a7": write tcp 172.17.0.2:58918->140.82.113.33:443: write: connection reset by peer
```

As documented in the [issue I mentioned above](https://github.com/felddy/foundryvtt-docker/issues/358), I have tried several other resolutions:
- Separating build from push steps
- Rolling back to the previous version of moby/buildkit
- Invalidating the cache
- Disabling the [step-security/harden-runner](https://github.com/step-security/harden-runner)

None of these had any effect.

#### Steps to reproduce this issue

1. Upgrade docker/setup-qemu-action to `v2`
1. Run the [build workflow](https://github.com/felddy/foundryvtt-docker/blob/develop/.github/workflows/build.yml) of the repository.

#### Expected behaviour

Docker images are published to Docker Hub, and Github container registry.

#### Actual behaviour

A Docker image is published to Docker Hub, but then has network failures push to ghrc.io

### Configuration

* Repository URL (if public): https://github.com/felddy/foundryvtt-docker
* Build URL (if public): https://github.com/felddy/foundryvtt-docker/runs/6630906077?check_suite_focus=true

```yml
---
name: build
# https://github.com/docker/build-push-action#complete-workflow

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
  schedule:
    - cron: '0 10 * * *'  # everyday at 10am
  repository_dispatch:
    # Respond to rebuild requests. See: https://github.com/cisagov/action-apb/
    types: [apb]
  workflow_dispatch:
    inputs:
      remote-shell:
        description: "Debug with remote shell"
        required: true
        default: false
      image-tag:
        description: "Tag to apply to pushed images"
        required: true
        default: dispatch

permissions:
  actions: read
  contents: read

env:
  BUILDX_CACHE_DIR: ~/.cache/buildx
  CURL_CACHE_DIR: ~/.cache/curl
  IMAGE_NAME: felddy/foundryvtt
  PIP_CACHE_DIR: ~/.cache/pip
  PLATFORMS: "linux/amd64,linux/arm/v6,linux/arm/v7,\
  linux/arm64,linux/ppc64le,linux/s390x"
  PRE_COMMIT_CACHE_DIR: ~/.cache/pre-commit
  RUN_TMATE: ${{ secrets.RUN_TMATE }}

jobs:
  lint:
    # Checks out the source and runs pre-commit hooks.  Detects coding errors
    # and style deviations.
    name: "Lint sources"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit

      - id: setup-env
        uses: cisagov/setup-env-github-action@a1913cd974407cd92d5b015342aa6d28d36539b8
      - uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16
      - id: setup-python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
        with:
          python-version: 3.9
      # We need the Go version and Go cache location for the actions/cache step,
      # so the Go installation must happen before that.
      - uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2
        with:
          go-version: '1.16'
      - name: Store installed Go version
        id: go-version
        run: |
          echo "::set-output name=version::"\
          "$(go version | sed 's/^go version go\([0-9.]\+\) .*/\1/')"
      - name: Lookup Go cache directory
        id: go-cache
        run: |
          echo "::set-output name=dir::$(go env GOCACHE)"
      - uses: actions/cache@730dc31003a72af3c3b4bf51268c167ad4c67ad6
        env:
          BASE_CACHE_KEY: "${{ github.job }}-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-\
            go${{ steps.go-version.outputs.version }}-\
            packer${{ steps.setup-env.outputs.packer-version }}-\
            tf${{ steps.setup-env.outputs.terraform-version }}-"
        with:
          path: |
            ${{ env.PIP_CACHE_DIR }}
            ${{ env.PRE_COMMIT_CACHE_DIR }}
            ${{ env.CURL_CACHE_DIR }}
            ${{ steps.go-cache.outputs.dir }}
          key: "${{ env.BASE_CACHE_KEY }}\
            ${{ hashFiles('**/requirements-test.txt') }}-\
            ${{ hashFiles('**/requirements.txt') }}-\
            ${{ hashFiles('**/.pre-commit-config.yaml') }}"
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Setup curl cache
        run: mkdir -p ${{ env.CURL_CACHE_DIR }}
      - name: Install shfmt
        env:
          PACKAGE_URL: mvdan.cc/sh/v3/cmd/shfmt
          PACKAGE_VERSION: ${{ steps.setup-env.outputs.shfmt-version }}
        run: go install ${PACKAGE_URL}@${PACKAGE_VERSION}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Set up pre-commit hook environments
        run: pre-commit install-hooks
      - name: Run pre-commit on all files
        run: pre-commit run --all-files
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270
        if: env.RUN_TMATE
  prepare:
    # Calculates and publishes outputs that are used by other jobs.
    #
    # Outputs:
    #   created:
    #     The current date-time in RFC3339 format.
    #   repometa:
    #     The json metadata describing this repository.
    #   source_version:
    #     The source version as reported by the `bump_version.sh show` command.
    #   tags:
    #     A comma separated list of Docker tags to be applied to the images on
    #     Docker Hub.  The tags will vary depending on:
    #     - The event that triggered the build.
    #     - The branch the build is based upon.
    #     - The git tag the build is based upon.
    #
    #     When a build is based on a git tag of the form `v*.*.*` the image will
    #     be tagged on Docker Hub with multiple levels of version specificity.
    #     For example, a git tag of `v1.2.3+a` will generate Docker tags of
    #     `:1.2.3_a`, `:1.2.3`, `:1.2`, `:1`, and `:latest`.
    #
    #     Builds targeting the default branch will be tagged with `:edge`.
    #
    #     Builds from other branches will be tagged with the branch name. Solidi
    #     (`/` characters - commonly known as slashes) in branch names are
    #     replaced with hyphen-minuses (`-` characters) in the Docker tag.  For
    #     more information about the solidus see these links:
    #       * https://www.compart.com/en/unicode/U+002F
    #       * https://en.wikipedia.org/wiki/Slash_(punctuation)#Encoding
    #
    #     Builds triggered by a push event are tagged with a short hash in the
    #     form: sha-12345678
    #
    #     Builds triggered by a pull request are tagged with the pull request
    #     number in the form pr-123.
    #
    #     Builds triggered using the GitHub GUI (workflow_dispatch) are tagged
    #     with the value specified by the user.
    #
    #     Scheduled builds are tagged with `:nightly`.
    name: "Prepare build variables"
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.prep.outputs.created }}
      repometa: ${{ steps.repo.outputs.result }}
      source_version: ${{ steps.prep.outputs.source_version }}
      tags: ${{ steps.prep.outputs.tags }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit

      - uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16
      - name: Gather repository metadata
        id: repo
        uses: actions/github-script@7f4e771d2b3022fa3b8bac499d4a547619f3ab10
        with:
          script: |
            const repo = await github.rest.repos.get(context.repo)
            return repo.data
      - name: Calculate output values
        id: prep
        run: |
          VERSION=noop
          SEMVER="^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION=${{ github.event.inputs.image-tag }}
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ];
              then
              VERSION=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          if [[ $VERSION =~ $SEMVER ]]; then
            VERSION_NO_V=${VERSION#v}
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            TAGS="${IMAGE_NAME}:${VERSION_NO_V//+/_},${IMAGE_NAME}:${MAJOR}.${MINOR}.${PATCH},${IMAGE_NAME}:${MAJOR}.${MINOR},${IMAGE_NAME}:${MAJOR}"
            source image_tags.sh
          else
            TAGS="${IMAGE_NAME}:${VERSION}"
          fi
          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="${TAGS},${IMAGE_NAME}:sha-${GITHUB_SHA::8}"
          fi
          for i in ${TAGS//,/ }
          do
            TAGS="${TAGS},ghcr.io/${i}"
          done
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=source_version::$(./bump_version.sh show)
          echo ::set-output name=tags::${TAGS}
          echo tags=${TAGS}
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270
        if: github.event.inputs.remote-shell == 'true' || env.RUN_TMATE
  check-docker-secrets:
    name: "Check Docker secrets"
    runs-on: ubuntu-latest
    steps:
      - name: check-secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] ||
            [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "::warning::Set DOCKER_USERNAME and DOCKER_PASSWORD secrets."
            exit 1
          fi
  check-foundry-secrets:
    name: "Check Foundry secrets"
    runs-on: ubuntu-latest
    steps:
      - name: check-secrets
        run: |
          if [ -z "${{ secrets.FOUNDRY_USERNAME }}" ] ||
            [ -z "${{ secrets.FOUNDRY_PASSWORD }}" ]; then
            echo "::warning::Set FOUNDRY_USERNAME and FOUNDRY_PASSWORD secrets."
            exit 1
          fi
  build-normal:
    # Builds a single test image for the native platform.  This image is saved
    # as an artifact and loaded by the test job.
    name: "Build normal test image"
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
      - name: Cache Docker layers
        uses: actions/cache@730dc31003a72af3c3b4bf51268c167ad4c67ad6
        env:
          BASE_CACHE_KEY: buildx-${{ runner.os }}-
        with:
          path: ${{ env.BUILDX_CACHE_DIR }}
          key: ${{ env.BASE_CACHE_KEY }}${{ github.sha }}
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Create dist directory
        run: mkdir -p dist
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          build-args: |
            VERSION=${{ needs.prepare.outputs.source_version }}
          cache-from: type=local,src=${{ env.BUILDX_CACHE_DIR }}
          cache-to: type=local,dest=${{ env.BUILDX_CACHE_DIR }}
          context: .
          file: ./Dockerfile
          outputs: type=docker,dest=dist/image.tar
          tags: ${{ env.IMAGE_NAME }}:latest  # not to be pushed
          # For a list of pre-defined annotation keys and value types see:
          # https://github.com/opencontainers/image-spec/blob/master/annotations.md
          labels: "\
            org.opencontainers.image.created=${{
              needs.prepare.outputs.created }}

            org.opencontainers.image.description=${{
              fromJson(needs.prepare.outputs.repometa).description }}

            org.opencontainers.image.licenses=${{
              fromJson(needs.prepare.outputs.repometa).license.spdx_id }}

            org.opencontainers.image.revision=${{ github.sha }}

            org.opencontainers.image.source=${{
              fromJson(needs.prepare.outputs.repometa).clone_url }}

            org.opencontainers.image.title=${{
              fromJson(needs.prepare.outputs.repometa).name }}

            org.opencontainers.image.url=${{
              fromJson(needs.prepare.outputs.repometa).html_url }}

            org.opencontainers.image.version=${{
              needs.prepare.outputs.source_version }}"
      - name: Compress image
        run: gzip dist/image.tar
      - name: Upload artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: dist-normal
          path: dist
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270
        if: env.RUN_TMATE
  build-pre-install:
    name: "Build pre-installed test image"
    runs-on: ubuntu-latest
    needs: [prepare, check-foundry-secrets]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
      - name: Cache Docker layers
        uses: actions/cache@730dc31003a72af3c3b4bf51268c167ad4c67ad6
        env:
          BASE_CACHE_KEY: buildx-${{ runner.os }}-
        with:
          path: ${{ env.BUILDX_CACHE_DIR }}
          key: ${{ env.BASE_CACHE_KEY }}${{ github.sha }}
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Create dist directory
        run: mkdir -p dist
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          build-args: |
            FOUNDRY_PASSWORD=${{ secrets.FOUNDRY_PASSWORD }}
            FOUNDRY_USERNAME=${{ secrets.FOUNDRY_USERNAME }}
            VERSION=${{ needs.prepare.outputs.source_version }}
          cache-from: type=local,src=${{ env.BUILDX_CACHE_DIR }}
          cache-to: type=local,dest=${{ env.BUILDX_CACHE_DIR }}
          context: .
          file: ./Dockerfile
          outputs: type=docker,dest=dist/image.tar
          tags: ${{ env.IMAGE_NAME }}:latest  # not to be pushed
          # For a list of pre-defined annotation keys and value types see:
          # https://github.com/opencontainers/image-spec/blob/master/annotations.md
          labels: "\
            org.opencontainers.image.created=${{
              needs.prepare.outputs.created }}

            org.opencontainers.image.description=${{
              fromJson(needs.prepare.outputs.repometa).description }}

            org.opencontainers.image.licenses=${{
              fromJson(needs.prepare.outputs.repometa).license.spdx_id }}

            org.opencontainers.image.revision=${{ github.sha }}

            org.opencontainers.image.source=${{
              fromJson(needs.prepare.outputs.repometa).clone_url }}

            org.opencontainers.image.title=${{
              fromJson(needs.prepare.outputs.repometa).name }}

            org.opencontainers.image.url=${{
              fromJson(needs.prepare.outputs.repometa).html_url }}

            org.opencontainers.image.version=${{
              needs.prepare.outputs.source_version }}"
      - name: Compress image
        run: gzip dist/image.tar
      - name: Upload artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: dist-pre-install
          path: dist
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270
        if: env.RUN_TMATE
  test-normal:
    # Executes tests on the single-platform image created in the "build" job.
    name: "Test normal image"
    runs-on: ubuntu-latest
    needs: [build-normal, check-foundry-secrets]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit

      - uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16
      - id: setup-python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
        with:
          python-version: 3.9
      - name: Cache testing environments
        uses: actions/cache@730dc31003a72af3c3b4bf51268c167ad4c67ad6
        env:
          BASE_CACHE_KEY: "${{ github.job }}-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-"
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "${{ env.BASE_CACHE_KEY }}\
            ${{ hashFiles('**/requirements-test.txt') }}-\
            ${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Download docker image artifact
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: dist-normal
          path: dist-normal
      - name: Load docker image
        run: docker load < dist-normal/image.tar.gz
      - name: Set data directory permissions
        run: |
          chmod a+rwx data
      - name: Run tests
        env:
          FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}
          FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: pytest --runslow
      - name: Upload data artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: data-normal
          path: data
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270
        if: env.RUN_TMATE
  test-pre-install:
    # Executes tests on the single-platform image created in the "build" job.
    name: "Test pre-installed image"
    runs-on: ubuntu-latest
    needs: [build-pre-install]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit

      - uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16
      - id: setup-python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
        with:
          python-version: 3.9
      - name: Cache testing environments
        uses: actions/cache@730dc31003a72af3c3b4bf51268c167ad4c67ad6
        env:
          BASE_CACHE_KEY: "${{ github.job }}-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-"
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "${{ env.BASE_CACHE_KEY }}\
            ${{ hashFiles('**/requirements-test.txt') }}-\
            ${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Download docker image artifact
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: dist-pre-install
          path: dist-pre-install
      - name: Load docker image
        run: docker load < dist-pre-install/image.tar.gz
      - name: Set data directory permissions
        run: |
          chmod a+rwx data
      - name: Run tests
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: pytest --runslow
      - name: Upload data artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: data-pre-install
          path: data
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270
        if: env.RUN_TMATE
  build-push-all:
    # Builds the final set of images for each of the platforms listed in
    # PLATFORMS environment variable.  These images are tagged with the Docker
    # tags calculated in the "prepare" job and pushed to Docker Hub and the
    # GitHub Container Registry.  The contents of README.md are pushed as the
    # image's description to Docker Hub.  This job is skipped when the
    # triggering event is a pull request.
    name: "Build and push all platforms"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [lint, prepare, test-normal, test-pre-install, check-docker-secrets]
    if: github.event_name != 'pull_request'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit

      - name: Login to Docker Hub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
      - name: Cache Docker layers
        uses: actions/cache@730dc31003a72af3c3b4bf51268c167ad4c67ad6
        env:
          BASE_CACHE_KEY: buildx-${{ runner.os }}-
        with:
          path: ${{ env.BUILDX_CACHE_DIR }}
          key: ${{ env.BASE_CACHE_KEY }}${{ github.sha }}
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Create cross-platform support Dockerfile-x
        run: ./buildx-dockerfile.sh
      - name: Build and push platform images to registries
        id: docker_build
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          build-args: |
            VERSION=${{ needs.prepare.outputs.source_version }}
          cache-from: type=local,src=${{ env.BUILDX_CACHE_DIR }}
          cache-to: type=local,dest=${{ env.BUILDX_CACHE_DIR }}
          context: .
          file: ./Dockerfile-x
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ needs.prepare.outputs.tags }}
          # For a list of pre-defined annotation keys and value types see:
          # https://github.com/opencontainers/image-spec/blob/master/annotations.md
          labels: "\
            org.opencontainers.image.created=${{
              needs.prepare.outputs.created }}

            org.opencontainers.image.description=${{
              fromJson(needs.prepare.outputs.repometa).description }}

            org.opencontainers.image.licenses=${{
              fromJson(needs.prepare.outputs.repometa).license.spdx_id }}

            org.opencontainers.image.revision=${{ github.sha }}

            org.opencontainers.image.source=${{
              fromJson(needs.prepare.outputs.repometa).clone_url }}

            org.opencontainers.image.title=${{
              fromJson(needs.prepare.outputs.repometa).name }}

            org.opencontainers.image.url=${{
              fromJson(needs.prepare.outputs.repometa).html_url }}

            org.opencontainers.image.version=${{
              needs.prepare.outputs.source_version }}"
      - name: Publish README.md to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: ./push_readme.sh
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270
        if: env.RUN_TMATE
```

### Logs

[logs_2471.zip](https://github.com/docker/setup-qemu-action/files/8789517/logs_2471.zip)

Thank you for your time.
