### ISSUE TITLE
getting no such file or directory on buildjet-2vcpu-ubuntu-2204 runner.

### ISSUE THREAD

**Issue by rhyek** [docker/setup-qemu-action#65]
### Behaviour

Recently getting this error. Started I believe on friday last week. It was working fine before on the same runner.

```yml
# paste your YAML workflow file here and remove sensitive data
      - name: Set up QEMU
        if: steps.needs-build.outputs.result == 'true'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
```

### Logs
![image](https://user-images.githubusercontent.com/702922/205703502-2f553e03-2af1-4097-ae36-9668c249987f.png)

[logs_3402.zip](https://github.com/docker/setup-qemu-action/files/10156499/logs_3402.zip)
