### ISSUE TITLE
Unable to use Action in Self Hosted Linux Containers

### ISSUE THREAD

**Issue by twistedpair** [docker/setup-qemu-action#67]
### Behaviour

Unable to use this Action, running on a self hosted runner with rootless Docker in Docker running in privileged mode.

Can you provide any guidance or examples of Linux based DinD self hosted runner images that work with this step?

#### Steps to reproduce this issue

1. Build a custom Linux GitHub runner base image with Docker In Docker (rootless)
2. Also install `qemu-user-static`
3. Use the `docker/setup-qemu-action@v2` action in your runner build

#### Expected behaviour

The step will be able to run in a Linux container based self hosted runner.

#### Actual behaviour

QEMU step fails.

If this step isn't used, all other Docker/Docker Buildx steps work fine with this docker image.

### Configuration

Note: `/proc/sys/fs/binfmt_misc` is present in the image, owned by root.
```
  ...
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
```

### Logs

```
Installing QEMU static binaries
  /usr/bin/docker run --rm --privileged tonistiigi/binfmt:latest --install all
  error: operation not permitted
  cannot mount binfmt_misc filesystem at /proc/sys/fs/binfmt_misc
  main.run
  	/src/cmd/binfmt/main.go:183
  main.main
  	/src/cmd/binfmt/main.go:170
  runtime.main
  	/usr/local/go/src/runtime/proc.go:250
  runtime.goexit
  	/usr/local/go/src/runtime/asm_amd64.s:1571
Extracting available platforms
```

**Comment by mmckane** [comment]
We are also seeing this, is it possible to run this in rootless docker?

**Comment by rodgerhe** [comment]
You can install the QEMU using apt-get. Add a step to your workflow.
```yml
     # Install QEMU-based emulator
      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
```

**Comment by lstellway** [comment]
After including the above step to install the `qemu-user-static` package, I have a step to output the available build platforms:

```yml
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
```

The available platforms shown are:

```txt
linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/386
```

As mentioned in [another issue I opened](https://github.com/catthehacker/docker_images/issues/112), it looks like the Debian QEMU install / mount directory is different: 

```txt
/usr/share/binfmts/
```

It looks like related files are present:

<details>
<summary>ls -l /usr/share/binfmts/</summary>

```txt
python3.10
qemu-sh4
qemu-microblaze
qemu-alpha
qemu-loongarch64
qemu-armeb
qemu-sparc32plus
qemu-microblazeel
qemu-aarch64_be
qemu-ppc
qemu-mipsn32
qemu-riscv64
qemu-mipsel
qemu-riscv32
qemu-sparc64
qemu-mipsn32el
qemu-ppc64
qemu-xtensa
qemu-aarch64
qemu-hppa
qemu-arm
qemu-mips64el
qemu-mips
qemu-ppc64le
qemu-or1k
qemu-hexagon
qemu-s390x
qemu-m68k
qemu-xtensaeb
qemu-mips64
qemu-sparc
qemu-sh4eb
```
</details>

Not the best representation, but my runner setup looks something like this:

```mermaid
graph LR

subgraph "Host (Debian)"
  subgraph "Docker (rootless)"
    RUNNER["Gitea runner\n+Docker (rootless)"]

    subgraph "DIND Containers"
      ACTION["Action runner\n(Ubuntu)"]
    end
  end
end


GITEA["Gitea Host"] -.-> RUNNER

%% Relationships
RUNNER -.-> |ghcr.io/catthehacker/ubuntu:act-latest| ACTION

click RUNNER "https://github.com/catthehacker/docker_images/pkgs/container/ubuntu"
```

**Comment by twistedpair** [comment]
Thanks @Istellway and @rodgerhe , I'm seeing the binfmt files, but not the same interpreter

> cat /usr/share/binfmts/qemu-arm
>>package qemu-user-static
interpreter /usr/libexec/qemu-binfmt/arm-binfmt-P
...


I'm running on Debian, with the `binfmt-support` and `qemu-user-static` libs installed

If I follow the instructions [here](https://github.com/catthehacker/docker_images/issues/112#issuecomment-1738346164) to run the QEMU Debian setup script, and mount `binfmt_misc` as root, then list the available 
platforms, there is no ARM support listed:

> docker buildx ls
>> default default         running v0.11.7+d3e6c1360f6e linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386



As such, using the latest actions, I'm still seeing the following error in the QEMU setup action

```yaml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
```

>  error: operation not permitted
  cannot mount binfmt_misc filesystem at /proc/sys/fs/binfmt_misc

Are there any other suggestions on how to get the QEMU setup step running from Debian containers? Thanks!
