### ISSUE TITLE
Qemu in Github Action Workflow with arm64 platform

### ISSUE THREAD

**Issue by 1fini** [docker/setup-qemu-action#69]
### Behaviour

 > [linux/arm64 publish 1/1] RUN dotnet publish "Automate.csproj" -c Release -o /app/publish:

/usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.Shared.targets(201,5): error MSB4063: The "CheckForDuplicateItems" task could not be initialized with its input parameters.  [/src/Automate/Automate.csproj]

#### Steps to reproduce this issue

1. Dockerfile with net7 app 
2. Qemu to build image for platform arm64 on GitHub Actions
3.

```yml
name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
        
    - name: Set up Docker Buildx
      id: docker_buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Build and push amd64 & arm64
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.docker_buildx.outputs.name}}
        context: .
        file: ./Automate/Dockerfile
        push: true
        platforms: linux/amd64, linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
```

### Logs

first paragraph

Regards
