### ISSUE TITLE
QEMU doesn't support linux/arm64/v8

### ISSUE THREAD

**Issue by rebeccaRossRobotics** [docker/setup-qemu-action#86]
### Behaviour
I am trying to build a docker image on the `linux/arm64/v8` platform through github action. under extracting available platforms this is not listed. Is this functionality going to be added soon?
My image is being run on a RaspberryPi CM4 with bulleye lite 64bit os on.

#### Steps to reproduce this issue
Dockerfiie to be built 
```
ARG ros_distro=humble
FROM --platform=$BUILDPLATFORM ros:${ros_distro}

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DOMAIN_ID=200
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

WORKDIR /home/$USER/mk4_ws/src
COPY . .
WORKDIR /home/$USER/mk4_ws
```
#### Expected behaviour

docker image should build with the architecture, variant and os as follows
```
"Architecture": "arm64",
"Variant": "v8",
"Os": "linux",
```

#### Actual behaviour

docker image is build with the architecture, variant and os as follows
```
"Architecture": "arm64",
"Os": "linux",
```
### Configuration

```
name: cli

on:
  push:
    branches: 265-make-a-docker-image-that-is-all-self-contained-for-the-mk4_ws

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64/v8, linux/amd64
          file: ./Dockerfile
          push: true
          tags: rossrobotics/mk4_test:github
```

### Logs

[logs_14.zip](https://github.com/docker/setup-qemu-action/files/11801148/logs_14.zip)
